name: Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
          package-name: model-mocker
          bump-minor-pre-major: true
          changelog-only: true 